FROM node:14

ENV ACCOUNT_MIN_CHAT_AGE 0
ENV ADMIN_EMAIL thiago@asupernova.com.br
ENV AMAZON_PAYMENTS_CLIENT_ID CLIENT_ID
ENV AMAZON_PAYMENTS_MODE sandbox
ENV AMAZON_PAYMENTS_MWS_KEY MWS_KEY
ENV AMAZON_PAYMENTS_MWS_SECRET MWS_SECRET
ENV AMAZON_PAYMENTS_SELLER_ID SELLER_ID
ENV AMPLITUDE_KEY AMPLITUDE_KEY
ENV AMPLITUDE_SECRET AMPLITUDE_SECRET
ENV BASE_URL https://rpg.auvp.com.br
ENV CRON_SAFE_MODE false
ENV CRON_SEMI_SAFE_MODE false
ENV DISABLE_REQUEST_LOGGING true
ENV EMAILS_COMMUNITY_MANAGER_EMAIL admin@habitica.com
ENV EMAILS_PRESS_ENQUIRY_EMAIL admin@habitica.com
ENV EMAILS_TECH_ASSISTANCE_EMAIL admin@habitica.com
ENV EMAIL_SERVER_AUTH_PASSWORD password
ENV EMAIL_SERVER_AUTH_USER user
ENV EMAIL_SERVER_URL http://example.com
ENV ENABLE_CONSOLE_LOGS_IN_PROD false
ENV ENABLE_CONSOLE_LOGS_IN_TEST false
ENV FACEBOOK_KEY 123456789012345
ENV FACEBOOK_SECRET aaaabbbbccccddddeeeeffff00001111
ENV FLAG_REPORT_EMAIL email@example.com, email2@example.com
ENV GA_ID GA_ID
ENV GOOGLE_CLIENT_ID 123456789012345
ENV GOOGLE_CLIENT_SECRET aaaabbbbccccddddeeeeffff00001111
ENV IAP_GOOGLE_KEYDIR /path/to/google/public/key/dir/
ENV IGNORE_REDIRECT true
ENV ITUNES_SHARED_SECRET aaaabbbbccccddddeeeeffff00001111
ENV LOGGLY_CLIENT_TOKEN token
ENV LOGGLY_SUBDOMAIN example-subdomain
ENV LOGGLY_TOKEN example-token
ENV MAINTENANCE_MODE false
ENV NODE_DB_URI mongodb://localhost:27017/habitica-dev?replicaSet=rs
ENV TEST_DB_URI mongodb://localhost:27017/habitica-test?replicaSet=rs
ENV MONGODB_POOL_SIZE 10
ENV NODE_ENV production
ENV PATH bin:node_modules/.bin:/usr/local/bin:/usr/bin:/bin
ENV PAYPAL_BILLING_PLANS_basic_12mo basic_12mo
ENV PAYPAL_BILLING_PLANS_basic_3mo basic_3mo
ENV PAYPAL_BILLING_PLANS_basic_6mo basic_6mo
ENV PAYPAL_BILLING_PLANS_basic_earned basic_earned
ENV PAYPAL_BILLING_PLANS_google_6mo google_6mo
ENV PAYPAL_CLIENT_ID client_id
ENV PAYPAL_CLIENT_SECRET client_secret
ENV PAYPAL_EXPERIENCE_PROFILE_ID xp_profile_id
ENV PAYPAL_MODE sandbox
ENV PLAY_API_ACCESS_TOKEN aaaabbbbccccddddeeeeffff00001111
ENV PLAY_API_CLIENT_ID aaaabbbbccccddddeeeeffff00001111
ENV PLAY_API_CLIENT_SECRET aaaabbbbccccddddeeeeffff00001111
ENV PLAY_API_REFRESH_TOKEN aaaabbbbccccddddeeeeffff00001111
ENV PORT 3000
ENV PUSH_CONFIGS_APN_ENABLED false
ENV PUSH_CONFIGS_APN_KEY xxxxxxxxxx
ENV PUSH_CONFIGS_APN_KEY_ID xxxxxxxxxx
ENV PUSH_CONFIGS_APN_TEAM_ID aaabbbcccd
ENV PUSH_CONFIGS_FCM_SERVER_API_KEY aaabbbcccd
ENV S3_ACCESS_KEY_ID accessKeyId
ENV S3_BUCKET bucket
ENV S3_SECRET_ACCESS_KEY secretAccessKey
ENV SESSION_SECRET YOUR SECRET HERE
ENV SESSION_SECRET_IV 12345678912345678912345678912345
ENV SESSION_SECRET_KEY 1234567891234567891234567891234567891234567891234567891234567891
ENV SITE_HTTP_AUTH_ENABLED false
ENV SITE_HTTP_AUTH_PASSWORDS password,wordpass,passkey
ENV SITE_HTTP_AUTH_USERNAMES admin,tester,contributor
ENV SLACK_FLAGGING_FOOTER_LINK https://habitrpg.github.io/flag-o-rama/
ENV SLACK_FLAGGING_URL https://hooks.slack.com/services/id/id/id
ENV SLACK_SUBSCRIPTIONS_URL https://hooks.slack.com/services/id/id/id
ENV SLACK_URL https://hooks.slack.com/services/some-url
ENV STRIPE_API_KEY aaaabbbbccccddddeeeeffff00001111
ENV STRIPE_PUB_KEY 22223333444455556666777788889999
ENV STRIPE_WEBHOOKS_ENDPOINT_SECRET 111111
ENV TRANSIFEX_SLACK_CHANNEL transifex
ENV WEB_CONCURRENCY 1
ENV SKIP_SSL_CHECK_KEY key
ENV ENABLE_STACKDRIVER_TRACING false
ENV LOG_AMPLITUDE_EVENTS false
ENV RATE_LIMITER_ENABLED false
ENV REDIS_HOST aaabbbcccdddeeefff
ENV REDIS_PORT 1234
ENV REDIS_PASSWORD 12345678


# Install global packages
RUN npm install -g gulp-cli mocha

# Clone Habitica repo and install dependencies
RUN mkdir -p /usr/src/habitrpg
WORKDIR /usr/src/habitrpg
# RUN git clone --branch release --depth 1 https://github.com/HabitRPG/habitica.git /usr/src/habitrpg
COPY . /usr/src/habitrpg
RUN git config --global url."https://".insteadOf git://
RUN npm set unsafe-perm true
RUN npm install

# Start Habitica
EXPOSE 80 8080 36612
CMD ["node", "./website/transpiled-babel/index.js"]
